ALTER TABLE press_releases ADD COLUMN IF NOT EXISTS price_at_creation INTEGER NOT NULL DEFAULT 0;
ALTER TABLE press_releases ADD COLUMN IF NOT EXISTS lingering_total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE press_releases ADD COLUMN IF NOT EXISTS lingering_remaining INTEGER NOT NULL DEFAULT 0;
